document.getElementById("year").textContent = new Date().getFullYear();

const navToggle = document.getElementById("navToggle");
const navLinks = document.getElementById("navLinks");

navToggle.addEventListener("click", () => {
  navLinks.classList.toggle("open");
});

navLinks.querySelectorAll("a").forEach((link) => {
  link.addEventListener("click", () => {
    navLinks.classList.remove("open");
  });
});

const MODULES = [
  {
    id: 1,
    name: "LLM Foundations",
    lessons: [
      {
        title: "How LLMs actually generate text",
        duration: "3 min",
        script: [
          "An LLM doesn't \"know\" an answer and recall it. At every step, it looks at the text so far and predicts a probability distribution over the next token — a word or word-fragment — then samples from that distribution and repeats.",
          "That single mechanism explains a lot of what you see in production. Hallucination isn't a glitch bolted onto a correct process; it's the same next-token prediction running with no grounding in fact, so a fluent, confident-sounding sentence and a fabricated one are generated by the identical mechanism.",
          "It also explains why phrasing changes outputs, why the same prompt can give different answers, and why a model can be extremely fluent and extremely wrong at the same time. When you're in a review and someone says \"the model should just know this,\" this is the concept to bring up.",
        ],
      },
      {
        title: "Context windows & why they break products",
        duration: "3 min",
        script: [
          "A context window is the maximum amount of text — measured in tokens, not characters or words — that a model can consider at once, counting the system prompt, conversation history, any retrieved documents, and the model's own output.",
          "When a conversation or document set exceeds that limit, something has to give: older messages get truncated, retrieved context gets cut short, or the request fails outright. This is why long support chats \"forget\" earlier details, and why RAG answers degrade when too many documents are stuffed in at once.",
          "There's a second, subtler failure mode: models are measurably weaker at using information buried in the middle of a long context than information near the start or end — often called the \"lost in the middle\" effect. So a bigger context window doesn't just mean \"more capacity\" — it means engineering has to actively decide what to keep, drop, or reorder, and that decision is a product decision as much as a technical one.",
        ],
      },
      {
        title: "Fine-tuning vs. prompting vs. RAG",
        duration: "3 min",
        script: [
          "These are the three main levers for changing what an LLM does, and they solve different problems. Prompting changes instructions at inference time — cheap, fast to iterate, but limited by what fits in the context window and by the model's existing knowledge.",
          "Fine-tuning adjusts the model's weights on your own examples. It's good for teaching a consistent style, format, or narrow behavior, but it's expensive to iterate on, doesn't reliably teach new facts, and can quietly degrade other capabilities if done carelessly.",
          "RAG keeps the base model frozen and instead retrieves relevant, current information at request time and feeds it into the prompt. It's the right lever when the problem is \"the model doesn't have access to this specific, changing information,\" not \"the model doesn't behave the way we want.\" A strong PM spec usually starts by naming which of these three problems is actually being solved, because teams frequently reach for fine-tuning when the real gap is retrieval.",
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Retrieval-Augmented Generation (RAG)",
    lessons: [
      {
        title: "RAG architecture end to end",
        duration: "3 min",
        script: [
          "A RAG pipeline has five stages, and each one is a place quality can quietly leak away. First, ingestion: documents come in from wherever they live — a wiki, a ticketing system, a set of PDFs — and get cleaned and parsed.",
          "Second, chunking splits that content into smaller pieces small enough to retrieve individually. Third, embedding turns each chunk into a vector that captures its meaning, and those vectors get stored in a vector database. Fourth, at query time, the user's question is embedded the same way and used to retrieve the most similar chunks.",
          "Fifth, generation: those retrieved chunks are inserted into the prompt, and the LLM writes an answer grounded in them. Because each stage feeds the next, a bad answer can originate from parsing that mangled a table, chunking that split a sentence in half, retrieval that missed the right document, or generation that ignored what it was given — and diagnosing which one requires tracing the pipeline, not just re-reading the final output.",
        ],
      },
      {
        title: "Chunking & embedding strategy",
        duration: "3 min",
        script: [
          "Chunk size is a trade-off, not a default setting. Small chunks retrieve precisely but lose surrounding context — a paragraph about pricing might get separated from the plan name it refers to. Large chunks preserve context but dilute the embedding, since a vector representing a whole page is a blurrier signal than one representing a focused paragraph.",
          "Overlap between consecutive chunks (typically 10–20%) exists specifically to stop this: without it, a fact that spans a chunk boundary can become unretrievable no matter how good the embedding model is.",
          "The embedding model itself matters too — general-purpose embeddings can miss domain vocabulary, and a model trained mostly on English will underperform on other languages or on heavy jargon. When a RAG system gives a wrong answer, checking the actual chunk boundaries around the relevant fact is often more revealing than checking the model's output.",
        ],
      },
      {
        title: "Why retrieval quality caps output quality",
        duration: "3 min",
        script: [
          "There's a simple ceiling effect in RAG: no matter how capable the generation model is, it can only work with what retrieval hands it. If the right document never makes it into the top results, the model is being asked to answer from the wrong material — and a good model will often still produce a fluent, confident answer built on it.",
          "This is why swapping in a more powerful LLM frequently fails to fix a RAG system that's underperforming. The bottleneck was never generation quality; it was recall — whether the relevant chunk was retrieved at all — or precision — whether the retrieved chunks were actually relevant, not just superficially similar in wording.",
          "So when a RAG answer is wrong, the productive question for a PM to ask isn't \"is the model good enough?\" It's \"was the right information even retrieved, and can we see what was actually passed to the model?\" That single question redirects most debugging conversations toward the real cause.",
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Evaluating LLM Systems",
    lessons: [
      {
        title: "Building a golden test set",
        duration: "3 min",
        script: [
          "A golden set is a curated collection of representative inputs paired with a known-correct or acceptable-range answer. It's the difference between an eval that means something and one that's just vibes — without it, \"the new prompt seems better\" is an opinion, not a measurement.",
          "Good golden sets are built from real usage, not invented from imagination: pull actual queries from logs, include edge cases and known failure modes, and make sure hard, ambiguous, and easy examples are all represented in the mix, not just the easy majority.",
          "They also need maintenance. As the product changes, the golden set goes stale — new features create new query types the set doesn't cover — so a healthy team treats it as a living asset with an owner, not a one-time deliverable from a launch six months ago.",
        ],
      },
      {
        title: "Offline vs. online evals",
        duration: "3 min",
        script: [
          "Offline evals run against a fixed golden set before anything ships — fast, repeatable, and ideal for catching regressions when a prompt, model, or retrieval step changes. Their limitation is that they can only test what's in the set; they can't see problems real users create through inputs nobody anticipated.",
          "Online evals measure live production signals instead: user feedback, thumbs up/down, escalation rates, follow-up questions that suggest confusion, or task completion. They catch what offline evals structurally can't, but they're slower, noisier, and arrive after the change is already live.",
          "Mature teams run both in sequence: offline evals gate a change before release, and online evals validate it against real behavior afterward. Relying on only one is a common gap — a team that only does offline evals gets blindsided by production reality, and a team that only watches production metrics ships regressions no dashboard catches until users complain.",
        ],
      },
      {
        title: "Reading an eval report like an engineer",
        duration: "3 min",
        script: [
          "A dashboard with an 85% pass rate tells you almost nothing on its own. The first question is what the metric is actually measuring — exact match, semantic similarity, an LLM-as-judge score — because each one fails differently and can be gamed differently.",
          "The second is where the failures cluster. An aggregate score hides pattern: if failures concentrate in one query type, one language, or one document source, that's a specific, fixable bug — not a reason to make sweeping changes across the whole system.",
          "The third is whether the eval method itself is trustworthy. LLM-as-judge scoring can have its own biases — favoring longer or more confident-sounding answers regardless of correctness — so a spot check of a sample of judged examples by a human is often worth more than the leaderboard number on its own.",
        ],
      },
    ],
  },
  {
    id: 4,
    name: "RAGAS & RAG-specific Metrics",
    lessons: [
      {
        title: "Faithfulness & hallucination detection",
        duration: "3 min",
        script: [
          "Faithfulness measures whether a generated answer is actually supported by the retrieved context, versus content the model added on its own. It's typically computed by breaking the answer into individual claims and checking each one against the retrieved chunks, then scoring the fraction that's actually grounded.",
          "A low faithfulness score is a strong hallucination signal — the model said something the retrieved material didn't say. But faithfulness only evaluates the generation step; it says nothing about whether the retrieved context itself was correct or complete in the first place.",
          "That's the trap teams fall into: a model can be perfectly faithful to context that was wrong, outdated, or irrelevant, and still score well on faithfulness while giving users a bad answer. Faithfulness measures one link in the chain, not the whole system.",
        ],
      },
      {
        title: "Context precision vs. context recall",
        duration: "3 min",
        script: [
          "These two RAGAS metrics answer different questions, and mixing them up leads to misdiagnosing problems. Context precision asks: of the chunks that were retrieved, how many were actually relevant? Low precision means retrieval is pulling in noise alongside the useful material.",
          "Context recall asks the opposite question: of all the relevant chunks that exist in the knowledge base, how many did retrieval actually find? Low recall means the system is missing information it needs, even if what it did retrieve was relevant.",
          "The fixes are different too. A precision problem usually points to re-ranking or tighter similarity thresholds. A recall problem usually points to chunking strategy, embedding quality, or gaps in the underlying knowledge base itself. Treating a recall problem as if it were a precision problem — for example, tightening thresholds when the real issue is that the right chunk was never indexed — makes the system worse, not better.",
        ],
      },
      {
        title: "When a high RAGAS score still means a bad product",
        duration: "3 min",
        script: [
          "RAGAS metrics are computed against the golden set and the retrieved context you gave the system — they can't see what they weren't shown. A high faithfulness score only means the answer matched the retrieved context; it says nothing about whether that context was the right context for what the user actually needed.",
          "A common real pattern: RAGAS scores look excellent because the golden set happens to be full of easy, well-covered queries, while real users ask messier, more varied questions the golden set never anticipated — and the metrics simply never see those failures.",
          "This is why RAGAS scores should always be read alongside user-facing signals: escalation rates, repeated follow-up questions, thumbs-down feedback. When the metrics say \"great\" and users say \"not helpful,\" the gap is almost always in what the golden set covers, not in the metric's math — and closing that gap means going back to real usage data, not tuning the eval further.",
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Prompting & System Design for PMs",
    lessons: [
      {
        title: "Writing a spec engineers won't rewrite",
        duration: "3 min",
        script: [
          "A spec that says \"use AI to answer support questions accurately\" forces engineering to make every real decision themselves — which means the spec wasn't actually specifying anything. A spec engineers can build from names the model or model class, the latency budget, and what happens when the model is uncertain or wrong.",
          "It should also state the fallback behavior explicitly: does the system escalate to a human, show a confidence caveat, or refuse to answer? And it should define what \"done\" means in testable terms — specific eval thresholds and example inputs the system needs to handle, not just a vibe.",
          "The details that seem like \"engineering's job\" — token budgets, timeout behavior, what happens under retrieval failure — are exactly the details that determine whether the feature works in the real world. A PM who can speak to those specifics, even at a high level, gets a fundamentally different quality of build than one who leaves them all unstated.",
        ],
      },
      {
        title: "Guardrails & structured output",
        duration: "3 min",
        script: [
          "LLMs naturally produce free-form text, but most products need something more constrained: a specific JSON shape, a bounded set of categories, or an answer that avoids certain topics entirely. Structured output techniques — schema-constrained generation, function calling, or output parsing with validation and retry — are how that gets enforced.",
          "Guardrails add a second layer on top: checking output before it reaches the user for safety issues, policy violations, or answers that fall outside the system's intended scope, sometimes using a second, smaller model as a fast classifier.",
          "Every one of these adds latency and cost, and an overly strict guardrail will reject valid answers just as often as a loose one lets bad ones through. The real design question for a PM isn't \"do we need guardrails\" — the answer is almost always yes — it's calibrating how strict, and being explicit about what failure mode the team is more willing to tolerate: false rejections or false approvals.",
        ],
      },
      {
        title: "Trade-offs: latency, cost, quality",
        duration: "3 min",
        script: [
          "These three variables move together, and a PM who understands the shape of that trade-off makes better calls than one who just asks for \"the best model.\" A larger, more capable model generally costs more per request and responds more slowly — sometimes meaningfully slower, which matters directly for anything conversational or real-time.",
          "Techniques like caching common queries, using a smaller model for easy cases and escalating hard ones to a larger model, or reducing how much context gets sent all shift this trade-off, but each comes with its own cost — engineering complexity, or a small quality hit on the cases that get routed to the cheaper path.",
          "There's rarely a single right answer here, only a right answer for a specific product's tolerance for slowness, spend, and error. Naming that tolerance explicitly, instead of leaving it implicit, is what turns a vague \"make it fast and good and cheap\" request into a decision engineering can actually design against.",
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Mock Technical Interviews",
    lessons: [
      {
        title: "\"Design a RAG system for support tickets\"",
        duration: "Mock, 20 min",
        script: [
          "This is a timed system-design mock interview. You'll be asked to design a RAG system that answers questions using a company's historical support tickets as its knowledge source — walking through ingestion, chunking, retrieval, and how you'd handle tickets that contradict each other or go stale over time.",
          "Strong answers name concrete choices instead of staying abstract: how tickets get chunked given their format, how outdated resolutions get filtered or down-weighted, and how the system behaves when no relevant ticket exists at all.",
          "After you outline your approach, compare it against the model answer and scoring rubric to see which trade-offs strong candidates surface that are easy to miss under time pressure — particularly around data freshness and conflicting information.",
        ],
      },
      {
        title: "\"How would you evaluate this chatbot?\"",
        duration: "Mock, 15 min",
        script: [
          "This mock interview asks you to design an evaluation plan from scratch for an existing chatbot, with no eval infrastructure currently in place. You'll need to decide what to measure, how to build a golden set, and how offline and online evaluation would work together.",
          "Strong answers anchor metrics to real product outcomes — task completion, escalation rate, faithfulness — rather than reaching for generic accuracy numbers that don't map to what the business actually cares about.",
          "Your plan is scored against what strong interviewers look for: whether you asked what \"good\" means for this specific product before proposing metrics, and whether your plan could realistically be built with the data the team already has.",
        ],
      },
      {
        title: "\"Our RAGAS scores look great but users are unhappy — why?\"",
        duration: "Mock, 15 min",
        script: [
          "This is a diagnostic-reasoning mock interview: RAGAS metrics look strong, but real users are dissatisfied, and you need to figure out why under time pressure — the exact gap covered in Module 4.",
          "Strong candidates don't guess at a single cause. They ask what the golden set actually covers, whether it reflects real query patterns, and what user-facing signals are diverging from the metrics before proposing a fix.",
          "The rubric rewards structured diagnosis over a confident-sounding guess — the same instinct that separates a PM who can credibly run a technical postmortem from one who can only repeat the dashboard numbers back.",
        ],
      },
    ],
  },
];

const allLessons = [];
MODULES.forEach((mod) => {
  mod.lessons.forEach((lesson, i) => {
    allLessons.push({ ...lesson, moduleName: mod.name, moduleId: mod.id, index: i });
  });
});

MODULES.forEach((mod) => {
  const list = document.getElementById(`module-${mod.id}`);
  if (!list) return;
  mod.lessons.forEach((lesson) => {
    const li = document.createElement("li");
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "lesson-btn";
    btn.innerHTML = `<span class="dot"></span> ${lesson.title} <em>${lesson.duration}</em>`;
    btn.addEventListener("click", () => {
      const globalIndex = allLessons.findIndex(
        (l) => l.moduleId === mod.id && l.title === lesson.title
      );
      openLesson(globalIndex);
    });
    li.appendChild(btn);
    list.appendChild(li);
  });
});

const modal = document.getElementById("lessonModal");
const modalBox = document.getElementById("modalBox");
const modalVideo = document.getElementById("modalVideo");
const modalModule = document.getElementById("modalModule");
const modalTitle = document.getElementById("lessonModalTitle");
const modalDesc = document.getElementById("modalDesc");
const modalDuration = document.getElementById("modalDuration");
const modalWatched = document.getElementById("modalWatched");
const modalPrev = document.getElementById("modalPrev");
const modalNext = document.getElementById("modalNext");
const modalClose = document.getElementById("modalClose");
const modalSize = document.getElementById("modalSize");
const modalFullscreen = document.getElementById("modalFullscreen");
const modalTextOnly = document.getElementById("modalTextOnly");
const playBtn = document.getElementById("playBtn");
const modalCaptions = document.getElementById("modalCaptions");
const noAudioWarning = document.getElementById("noAudioWarning");
const voiceSelect = document.getElementById("voiceSelect");

const speechSupported = "speechSynthesis" in window;
if (!speechSupported) noAudioWarning.hidden = false;

let currentIndex = 0;
let currentUtterance = null;
let selectedVoiceURI = null;

const SIZES = ["", "size-large", "size-xl"];
let sizeIndex = 0;

modalSize.addEventListener("click", () => {
  modalBox.classList.remove(...SIZES.filter(Boolean));
  sizeIndex = (sizeIndex + 1) % SIZES.length;
  if (SIZES[sizeIndex]) modalBox.classList.add(SIZES[sizeIndex]);
});

modalFullscreen.addEventListener("click", () => {
  if (document.fullscreenElement) {
    document.exitFullscreen();
  } else if (modalBox.requestFullscreen) {
    modalBox.requestFullscreen();
  }
});

document.addEventListener("fullscreenchange", () => {
  modalBox.classList.toggle("fullscreen-active", document.fullscreenElement === modalBox);
});

modalTextOnly.addEventListener("click", () => {
  const isTextOnly = modalBox.classList.toggle("text-only");
  modalTextOnly.classList.toggle("active", isTextOnly);
  if (isTextOnly) stopNarration();
});

let sortedVoices = [];
const brokenVoiceURIs = new Set();

function populateVoices() {
  if (!speechSupported) return;
  const voices = window.speechSynthesis.getVoices();
  if (!voices.length) return;

  // Local (on-device) voices work reliably offline; remote/network voices
  // often silently fail depending on the browser and embedding context, so
  // they're ranked after local ones even if their names sound "nicer".
  const rank = (v) => {
    if (!v.localService) return 2;
    return /natural|neural|enhanced|premium/i.test(v.name) ? 0 : v.lang.startsWith("en") ? 1 : 1.5;
  };
  sortedVoices = [...voices].sort((a, b) => rank(a) - rank(b));

  voiceSelect.innerHTML = "";
  sortedVoices.forEach((v) => {
    const opt = document.createElement("option");
    opt.value = v.voiceURI;
    const tag = v.localService ? "" : " ⚠ needs network";
    opt.textContent = `${v.name} (${v.lang})${tag}`;
    voiceSelect.appendChild(opt);
  });

  if (!selectedVoiceURI || !sortedVoices.some((v) => v.voiceURI === selectedVoiceURI)) {
    selectedVoiceURI = sortedVoices[0].voiceURI;
  }
  voiceSelect.value = selectedVoiceURI;
}

voiceSelect.addEventListener("change", () => {
  selectedVoiceURI = voiceSelect.value;
  brokenVoiceURIs.delete(selectedVoiceURI);
});

if (speechSupported) {
  populateVoices();
  window.speechSynthesis.onvoiceschanged = populateVoices;
}

function stopNarration() {
  clearTimeout(startTimer);
  clearInterval(watchdogInterval);
  if (speechSupported) window.speechSynthesis.cancel();
  modalVideo.classList.remove("playing");
  playBtn.textContent = "▶";
  modalCaptions.textContent = "";
}

function candidateVoices() {
  const voices = window.speechSynthesis.getVoices();
  if (!voices.length) return [null];
  const preferred = voices.find((v) => v.voiceURI === selectedVoiceURI);
  const fallbacks = sortedVoices.length ? sortedVoices : voices;
  const ordered = [preferred, ...fallbacks].filter(
    (v, i, arr) => v && !brokenVoiceURIs.has(v.voiceURI) && arr.findIndex((x) => x && x.voiceURI === v.voiceURI) === i
  );
  ordered.push(null); // last resort: browser default voice
  return ordered;
}

let startTimer = null;
let watchdogInterval = null;
let sentenceQueue = [];
let sentenceIndex = 0;

function splitSentences(text) {
  return (text.match(/[^.!?]+[.!?]*/g) || [text]).map((s) => s.trim()).filter(Boolean);
}

// Many speech engines (notably Chrome) silently stop mid-narration on long
// utterances. Nudging pause/resume periodically, plus speaking one sentence
// at a time, keeps the engine's internal queue from stalling.
function startWatchdog() {
  clearInterval(watchdogInterval);
  watchdogInterval = setInterval(() => {
    if (window.speechSynthesis.speaking && !window.speechSynthesis.paused) {
      window.speechSynthesis.pause();
      window.speechSynthesis.resume();
    }
  }, 10000);
}

function stopWatchdog() {
  clearInterval(watchdogInterval);
  watchdogInterval = null;
}

function finishNarration() {
  clearTimeout(startTimer);
  stopWatchdog();
  modalVideo.classList.remove("playing");
  playBtn.textContent = "▶";
  modalCaptions.textContent = "";
}

function speakAttempt(voiceQueue, queueIndex) {
  const sentence = sentenceQueue[sentenceIndex];

  if (queueIndex >= voiceQueue.length) {
    modalCaptions.textContent = "Audio isn't available on this device/browser — try Text Only above.";
    finishNarration();
    return;
  }

  const voice = voiceQueue[queueIndex];
  const utterance = new SpeechSynthesisUtterance(sentence);
  utterance.rate = 0.98;
  utterance.pitch = 1;
  if (voice) {
    utterance.voice = voice;
    utterance.lang = voice.lang;
  }

  let started = false;

  utterance.onstart = () => {
    started = true;
    clearTimeout(startTimer);
    modalVideo.classList.add("playing");
    playBtn.textContent = "⏸";
    modalCaptions.textContent = sentence;
  };

  utterance.onend = () => {
    clearTimeout(startTimer);
    sentenceIndex += 1;
    if (sentenceIndex >= sentenceQueue.length) {
      finishNarration();
    } else {
      speakAttempt(voiceQueue, 0);
    }
  };

  utterance.onerror = () => {
    clearTimeout(startTimer);
    if (voice) brokenVoiceURIs.add(voice.voiceURI);
    speakAttempt(voiceQueue, queueIndex + 1);
  };

  currentUtterance = utterance;
  window.speechSynthesis.speak(utterance);

  clearTimeout(startTimer);
  startTimer = setTimeout(() => {
    if (!started) {
      window.speechSynthesis.cancel();
      if (voice) brokenVoiceURIs.add(voice.voiceURI);
      speakAttempt(voiceQueue, queueIndex + 1);
    }
  }, 1500);
}

function playNarration(lesson) {
  if (!speechSupported) return;
  window.speechSynthesis.cancel();

  const text = `${lesson.title}. ${lesson.script.join(" ")}`;
  sentenceQueue = splitSentences(text);
  sentenceIndex = 0;
  startWatchdog();
  speakAttempt(candidateVoices(), 0);
}

function openLesson(index) {
  stopNarration();
  currentIndex = (index + allLessons.length) % allLessons.length;
  const lesson = allLessons[currentIndex];
  modalModule.textContent = `${lesson.moduleName} · Lesson ${lesson.index + 1}`;
  modalTitle.textContent = lesson.title;
  modalDesc.innerHTML = "";
  lesson.script.forEach((paragraph) => {
    const p = document.createElement("p");
    p.textContent = paragraph;
    modalDesc.appendChild(p);
  });
  modalDuration.textContent = lesson.duration;
  modalWatched.checked = false;
  modal.classList.add("open");
  modal.setAttribute("aria-hidden", "false");
  document.body.style.overflow = "hidden";
}

function closeLesson() {
  stopNarration();
  if (document.fullscreenElement === modalBox) document.exitFullscreen();
  modal.classList.remove("open");
  modal.setAttribute("aria-hidden", "true");
  document.body.style.overflow = "";
}

modalClose.addEventListener("click", closeLesson);
modal.addEventListener("click", (e) => {
  if (e.target === modal) closeLesson();
});
document.addEventListener("keydown", (e) => {
  if (e.key === "Escape" && modal.classList.contains("open")) closeLesson();
});

modalPrev.addEventListener("click", () => openLesson(currentIndex - 1));
modalNext.addEventListener("click", () => openLesson(currentIndex + 1));

playBtn.addEventListener("click", () => {
  if (!speechSupported) return;
  if (window.speechSynthesis.speaking && !window.speechSynthesis.paused) {
    window.speechSynthesis.pause();
    modalVideo.classList.remove("playing");
    playBtn.textContent = "▶";
  } else if (window.speechSynthesis.paused) {
    window.speechSynthesis.resume();
    modalVideo.classList.add("playing");
    playBtn.textContent = "⏸";
  } else {
    playNarration(allLessons[currentIndex]);
  }
});
